#!/bin/bash

project_dir=$(pwd)

# Get the operating system name
os_name=$(uname)

# Check if the operating system is UNIX-like
if [[ "$os_name" != "Linux" && "$os_name" != "Darwin" ]]; then
    echo "Error: This script requires a UNIX-like operating system (Linux or macOS) to run."
    exit 1
fi

# Check if PHP FFI is enabled
if ! php -m | grep -q 'FFI'; then
    echo "Error: PHP FFI extension is not enabled. Please enable PHP FFI to proceed."
    exit 1
fi

# Check if Rust and Cargo are installed
if ! command -v cargo &>/dev/null; then
    echo "Error: Rust and Cargo are required but not found. Please install Rust (including Cargo) to proceed."
    exit 1
fi

# Check if the C/C++ compiler is installed
if ! command -v cc &>/dev/null && ! command -v gcc &>/dev/null && ! command -v g++ &>/dev/null; then
    echo "Error: C/C++ compiler is required but not found. Please install a C/C++ compiler to proceed."
    exit 1
fi

echo "😎 OhMyPunk! You're using $os_name"
echo "+ PHP FFI Extention is enabled ✅"
echo "+ 🦀 + 📦 is ready ✅"
echo "+ C/C++ Compiler already setup! 🍻"
extension_dir="vendor/darkterminal/libsql-php-ext"
cd "$extension_dir" || exit

# Check if Cargo.toml file exists
if [ ! -f "Cargo.toml" ]; then
    echo "Error: Cargo.toml file not found in the extension directory. Please make sure it exists."
    exit 1
fi

echo "Building the extension..."
cargo build --release

echo "Checking if libs directory exists..."
if [ ! -d "libs" ]; then
    echo "Creating libs directory..."
    mkdir libs
fi

echo "Copying lib into libs directory..."
cp "target/release/libsql_php_client.so" libs/

echo "Copying The Intelephense Helper for you... 😊"
cp "$extension_dir/_intelephense_helper.php" "$project_dir/_intelephense_helper.php"

cd $project_dir

echo "Building the extension is done! ✨"
